config/routes.rb
Rails.application.routes.draw do
  
  
 

 resources :sessions, only: [:new, :create, :destroy]
 resources :gossips
 resources :users, only: [:show,:new,:create]
 resources :cities, only:[:show]
 resources :gossips do
 resources :comments, only:[ :new ,:create,:edit ]
end
  root 'gossips#index'
  get '/welcome/:id', to: 'welcome_page#welcome'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  # get '/:id', to: 'static_pages#gossip'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  # 1-N association with users table
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes

  validates :title,
  presence: true
  

  validates :content,
  presence: true
  
end

app/models/gossip_metum.rb
# the join table that maps the N-N association between gossips and tags
class GossipMetum < ApplicationRecord
  # 1-N association with gossips table
  belongs_to :gossip

  # 1-N association with tags table
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id
end

app/models/message_delivering.rb
# the join table that maps the N-N association between recipients and received_messages
class MessageDelivering < ApplicationRecord
  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  # 1-N association with senders (users) table
  belongs_to :sender, class_name: 'User'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :received_message_id

  # N-N association with recipients (users) table via message_deliverings table
  has_many :recipients, through: :message_deliverings, source: :recipient
end

app/models/tag.rb
class Tag < ApplicationRecord
  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with gossips table via gossips_meta table
  has_many :gossips, through: :gossip_meta
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  # 1-N association with gossips table
  has_many :gossips

  # 1-N association with sent_messages (private_messages) table
  # users renamed as senders for this association, class_name explains it to Rails
  has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :recipient_id

  # N-N association with received_messages (private_messages) table via the message_deliverings table
  # renamed as recipients but doesn't show here
  has_many :received_messages, through: :message_deliverings

  # 1-N associations with comments
  has_many :comments

  # 1-N associations with likes
  has_many :likes

  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])

  	@gossip = Gossip.all

  end
end
	

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end	
  
  def create
    
    

  end	

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new,:create,:edit,:destroy]
 
  def index 

    @gossips = Gossip.all

  end

  
  def show
  
    @gossip = Gossip.find(params[:id])
  
  end  

  def edit
  
    @gossip = Gossip.find(params[:id])

  end

 


  def new
   
    @gossip = Gossip.new
   
  end 

  def create
    
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: 2) # avec xxx qui sont les données obtenues à partir du formulaire
    
    @gossip.user = current_user

    if @gossip.save # essaie de sauvegarder en base @gossip
       flash[:notice] = "Post successfully created"
       redirect_to gossips_path
    else
       flash[:notice] = "Post fail"
       redirect_to new_gossip_path
    end

  end  
  
  def update
    
    @gossip = Gossip.find(params[:id])
    
    gossip_params = params.require(:gossip).permit(:title, :content)

    @gossip.update(gossip_params)

      if @gossip.update(gossip_params)
      
        redirect_to gossips_path

      else
        render :edit
      
      end
  end    

    def destroy
    @gossip = Gossip.find(params[:id]) 
    @gossip.destroy
    redirect_to root_path
  end

    private

    def authenticate_user
        unless current_user
          flash[:notice] = "Connectez-vous afin de pouvoir ajouter ou editer un potin "
          redirect_to new_session_path
        end
    end
  end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end	

	def create
		 # cherche s'il existe un utilisateur en base avec l’e-mail
  		user = User.find_by(email: params["email"])

  		# on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
  		if user && user.authenticate(params["password"])
   			 session[:user_id] = user.id
   			 flash[:notice] = "Session successfully created"
        	 redirect_to root_path
	    else
    		flash[:notice] = 'Invalid email/password combination'
    		render 'new' 
    		
  		end

	end
	
	def destroy

	  session.delete(:user_id)
  	  redirect_to root_path
  	  
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  
  end

  def new
  	@user = User.new
  end
  
  def create

    my_city = City.create(name:"undefined")

  	@user = User.new(email: params["email"],password: params["password"],city_id: my_city.id)

  	if @user.save # essaie de sauvegarder en base @user
      flash[:notice] = "User successfully created"
      redirect_to root_path# si ça marche, il redirige vers la page d'index du site
    else
      flash[:notice] = "User creation failed"
      redirect_to new_user_path 
    end

  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    	User.find_by(id: session[:user_id])
  	end

    def log_in(user)
        session[:user_id] = user.id
    end

    def logged_in?
   		if session[:user_id].nil?
           return false
        else
           return true
        end
    end

    def is_owner?(id)
    	return false if current_user.nil?
    	# fait une erreur sans un return false
    	return true if current_user.id == id
   	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/cities/show.html.erb
 <h3 class= "list-group"><%= @city.name%></h3>

<p class = "list-group"> Liste des potins de cette ville</p>

<div>

	<ul class="list-group">  <% @city.users.each do |u| %>

	<% u.gossips.each do |g|%>
		<li class ="list-group-item">  <%= u.first_name %></li>
		<li class ="list-group-item">  <%= g.title %> </li>
		<li class ="list-group-item">  <%= g.content %> </li>
   		<% end %>
 		<% end %>

    </ul>
</div> 

app/views/gossips/edit.html.erb
<h2>Editer le gossip</h2>

<%=form_for @gossip do |f|%>

	<div class= 'form-group'>
		<label>Title</label>
		<%= f.text_field :title, class:'form-control'%>
	</div>	

	<div class= 'form-group'>
		<label>Content</label>
		<%= f.text_area :content, class:'form-control'%>
	</div>

	<div>
		  <button type="submit" class ="btn btn-primary"> Modifier le gossip</button>

	</div>

<%end%>	

app/views/gossips/index.html.erb
<div>     
      <div class="alert alert-success alert-dismissible">
                <strong><%= flash[:notice] %></strong> 
      </div>              
</div>  


<% @gossips.each_with_index do |gossip,index| %>
  <div class="card">
    <div class="card-body">
      <p class="card-text"><%= gossip.title %></p>
      <p class="card-text"><%= gossip.user.first_name%></p>
      <!-- On propose les actions pertinentes en fonction du user -->
      <% if logged_in?%>
        <%= link_to "consulter", gossip_path(gossip[:id]), class: "card-link btn btn-primary" %>
        <%= link_to "modifier", edit_gossip_path(gossip[:id]), class: "card-link" %>
        <%= link_to "Supprimer", gossip_path(gossip[:id]), class: "card-link btn btn-danger", data:{confirm:"êtes vous sûr?", method: "DELETE"} %>
      <% else %>
        <%= link_to "consulter", gossip_path(gossip[:id]), class: "card-link btn btn-primary" %>
      <% end %>

    </div>
  </div>
  <br>
<% end %>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_tag gossips_path method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @title %>
      <br /> <br />

      <%= label_tag 'Content' %>
      <%= text_area_tag 'content', @content %>
      <br /> <br />

      <%= submit_tag "Create gossip" %>

    <% end %>

    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @gossip.title%></h5>
    <p class="card-text"><%= @gossip.content %></p>
    <p>Created by:<%= link_to @gossip.user.first_name, user_path(@gossip.user.id)%></span></p>
    <% if is_owner?(@gossip.user.id) %>
    <p> <%= link_to "Supprimer", gossip_path(:id => @gossip.id), data: { confirm: 'Are you sure?' }, method: :delete %></p>
    <%end%>   
          
  </div>


</div>

app/views/users/new.html.erb
<%= form_tag users_path, method: "post" do %>
    <!-- form_tag url_for(action:'create'), method: "post" do  -->
      <%= label_tag 'email' %>
      <%= text_field_tag 'email', @email %>
      <br /> <br />
      <%= label_tag 'Password' %>
      <%= text_field_tag 'password', @password %>
      <br /> <br />
      <%= submit_tag "Créer un compte" %>
    <% end %>
     <% if flash[:notice] %>
    <div class="alert alert-dismissible alert-danger">
    <div class="notice"><strong><%= flash[:notice] %></strong>
    </div>
   </div>
    
   <% end %>

app/views/users/show.html.erb
<div class="list-group">
	<p class="list-group-item">Ceci est le profil de <%= @user.first_name %></p>

     <ul class="list-group">
          <li class="list-group-item">First name:<%= @user.first_name %></li>
          <li class="list-group-item">Last name:<%= @user.last_name %></li>
          <li class="list-group-item">Description:<%= @user.description %></li>
          <li class="list-group-item">Email:<%= @user.email%></li>
          <li class="list-group-item">Age:<%= @user.age%></li>
          <li class="list-group-item">City:<%= link_to @user.city.name, city_path(@user.city.id)%></li>
         
     </ul>     
</div>